config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top" #root to: "homes/top"を"homes#top"にしないとエラー出るよ→Missing :controller key on routes definition, please check your routes. (ArgumentError)
  get "/home/about" => "homes#about", as: "about" #topページからaboutで飛ぶとこ_as:でabout_path,about_urlが作成される
  devise_for :users
  resources :books
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  #空でないように設定してください。
  validates:title, presence:true
  #空でない、かつ最大200文字までに設定してください。
  validates:body, presence:true,length:{maximum:200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books,dependent: :destroy
  has_one_attached :profile_image

  # name：一意性を持たせ、かつ2～20文字の範囲で設定してください。
  validates:name, presence:true, length:{minimum:2,maximum:20}, uniqueness:true
  # introduction：最大50文字までに設定してください。
  validates:introduction, length:{maximum:50}

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # 全てのアクションの前に、ユーザーがログインしているかどうか確認する！
  before_action :authenticate_user!, except: [:top, :about]
  # device利用の機能が使用される場合、:configure_permitted~が実行される
  before_action :configure_permitted_parameters,if: :devise_controller?

  # ログイン後マイページに移行
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  # ログアウト後トップページに移行
  def after_sign_out_path_for(resource)
    root_path
  end
  # 他のコントローラからも参照できる(ストロングパラメータの広域版-単域版はprivate)
  protected
  # sign_upの際にnameとemailが認証キー
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:name,:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # ログインしている状態だけ許可するアクションをonlyで指定
  before_action :authenticate_user!, only: [:index,:show,:edit,:create,:update,:destroy]

  def index
    @books=Book.all
    # index内に投稿を置く場合、newが必要
    @book = Book.new
    # ログイン中のユーザーを渡す
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    # booksのuser_idカラムは現在ログイン中のIDで保存する
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book)
      flash[:success]="You have created book successfully."
    else
      @books=Book.all
      @user = current_user
      render :index
    end
  end

  def show
    # show内（book詳細）に投稿を置く場合、newが必要
    @book_new = Book.new
    @book = Book.find(params[:id])
    # テンプレート化するために、@userに@book.userを格納
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
        redirect_to book_path(@book.id)
        flash[:success]="You have updated book successfully."
    else
      @books = Book.all
      render action: :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @books = Book.all
    # index内（ユーザー一覧）に投稿を置く場合、newが必要
    @book = Book.new
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    # @userに紐付いたbooksのみを表示
    @books = @user.books
    # show内（ユーザ詳細）に投稿を置く場合、newが必要
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
        render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
        redirect_to user_path(@user.id)
        flash[:success] = "You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_newbook.html.erb
<!--投稿フォーム、部分テンプレート-->
<h2 class="mt-3">New book</h2>
    <%= form_with model: book do |f| %>
    <div class="form-group">
      <label for="book_title">Title</label><br>
        <%= f.text_field :title %>
    </div>
    <div class="form-group">
      <label for="book_opinion">Opinion</label><br>
        <%= f.text_area :body %>
    </div>
    <div class="form-group">
         <%= f.submit 'Create Book', class:"btn btn-success" %>
        <% end %>
    </div>

app/views/books/edit.html.erb
<!--投稿フォーム-->
<div class="container pt-3 pb5">
  <div class="row">
   <div class="col-lg-5 mx-auto">

     <h2>Editing Book</h2>
       <%= form_with(model:@book, local: true) do |form| %>
          <% if @book.errors.any? %>
            <div id="error_explanation">
              <h3><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h3><ul>
              <ul>
                  <% @book.errors.full_messages.each do |message| %>
                   <li><%= message %></li>
                  <% end %>
             </ul>
            </div>
          <% end %>
       <% end %>

     <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>
       <div class="form-group">
         <label for="book_title">Title</label><br>
            <%= f.text_field :title %>
       </div>
       <div class="form-group">
         <label for="book_opinion">Opinion</label><br>
            <%= f.text_area :body %>
       </div>
       <div class="form-group">
            <%= f.submit 'Update Book',class:"btn btn-success" %>
       </div>

       <div class="link">
            <%= link_to "Show", book_path(@book.id) %>
            <%= " | " %>
            <%= link_to "Back", books_path %>
       </div>
     <% end %>
   </div>
  </div>
 </div>

app/views/books/index.html.erb
<!--本一覧ページ-->
<!--newbook作成時エラー文-->
<div class="container ">
    <% if @book.errors.any? %>
      <h3><%= @book.errors.count %> errors prohibited this book from being saved:</h3>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    <% end %>
</div>

<!--User info と New book欄（左側部分）-->
<div class="container pt-3 pb-5">
  <div class="row">
    <div class="col-md-3 pr-1">
    <%= render 'users/userinfo', user: @user %>

    <%= render 'books/newbook', book: @book %>
    </div>

   <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
            </tr>
          </thead>

          <% @books.each do |book| %>
          <tbody>
		        <tr>
		          <td>
		            <%= link_to user_path(book.user) do %>
		              <%= image_tag book.user.get_profile_image(80,80) %>
                <% end %>
              </td>

              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>

              <td>
                <%= book.body %>
              </td>

            </tr>
          </tbody>
        <% end %>
       </table>
   </div>
  </div>
</div>

app/views/books/show.html.erb
<!--本の詳細-->
<div class="container pt-3 pb-5">
  <div class="row">
    <div class="col-md-3 pr-1">

    <%= render 'users/userinfo', user: @user %>

    <%= render 'books/newbook', book: @book_new %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
        <div>
        <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user) do %>
                <%= image_tag @book.user.get_profile_image(100,100) %>
		          <% end %><br>

                <%= link_to @book.user.name,user_path(@book.user) %>
           </td>
           <td><%= link_to @book.title %></td>
           <td><%= @book.body %></td>
             <% if @book.user_id == current_user.id %>
              <td><%= link_to"Edit", edit_book_path(@book.id),class:"btn-sm btn-success" %></td>
              <td><%= link_to "Destroy", book_path(@book.id), class:"btn-sm btn-danger destroy(@book.id)", method: :delete,data: {confirm: "本当に消しますか？"} %></td>
             <% end %>
         </tr>
       </tbody>
       </table>
   </div>

app/views/homes/about.html.erb
<div class='container pt-4'>
  <div class='row'>
   <h1 class='px-3 mx-auto'>
     Welcome to
      <i class = "fas fa-book" ></i>
       <strong>Bookers</strong>!
    </h1>
   </div>
 </div>

app/views/homes/top.html.erb
<div class='container pt-3'>
  <div class='row'>
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6 p-2'>

     <h1>
       Welcome to
     <i class = "fas fa-book" ></i>
       <strong>Bookers</strong>!!
     </h1>
       <p>In
       <i class = "fas fa-book" ></i>
       <strong>Bookers</strong>,
       </p>
       <p>you can share and exchange your opinions , inpressions , and emotions</p>
       <p>about various books!</p>
     <div class='btn-wrapper col-10 mx-auto'>
      <div class='row'>
       <%= link_to "Log in", "/users/sign_in", class: "btn btn-info btn-sm btn-block mb-3 log_in" %>
      </div>
      <div class='row'>
       <%= link_to "Sign up", "/users/sign_up", class: "btn btn-success btn-sm btn-block sign_up" %>
      </div>
     </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
       <a class="navbar-brand" href= "/" >
        <span>Bookers</span>
       </a>

       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarNavDropdown">
       <ul class="navbar-nav ml-auto">

         <% if user_signed_in? %>
           <li><%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
           <i class="fas fa-home"></i> Home
               <% end %></li>
           <li><%= link_to "/users", class: 'nav-link text-light' do %>
           <i class="fas fa-users"></i> Users
               <% end %></li>
           <li><%= link_to books_path, class: 'nav-link text-light' do %>
           <i class="fas fa-book-open"></i> Books
               <% end %></li>
           <li><%= link_to destroy_user_session_path,method: :delete, class: 'nav-link text-light' do %>
           <i class="fas fa-sign-out-alt"></i> Log out
               <% end %></li>

         <% else %>
           <li><%= link_to root_path, class: 'nav-link text-light' do %>
           <i class="fas fa-home"></i> Home
               <% end %></li>
           <li><%= link_to about_path, class: 'nav-link text-light' do %>
           <i class="fas fa-link"></i> About
               <% end %></li>
           <li><%= link_to "/users/sign_up", class: 'nav-link text-light' do %>
           <i class="fas fa-user-plus"></i> Sign up
               <% end %></li>
           <li><%= link_to "/users/sign_in", class: 'nav-link text-light' do %>
           <i class="fas fa-sign-in-alt"></i> Log in
               <% end %></li>
         <% end %>
       </div>
   </header>

  <!--ログイン/ログアウトのフラッシュメッセージ-->
   <div class= "body">
     <% flash.each do |key, value| %>
       <%= content_tag(:div, value, class: "#{key}") %>
     <% end %>
   </div>
   <main>
     <%= yield %>
   </main>

   <footer>
     <div class='container mt-5'>
       <div class='row'>
         <div class='mx-auto'>
          <p>CopyRight Infratop.inc</p>
         </div>
       </div>
     </div>
   </footer>
 </body>
</html>

app/views/users/_userinfo.html.erb
<!--プロフィール画面、部分テンプレート-->
    <h2>User info</h2>
      <table class="table">
        <tr>
          <td><%= image_tag user.get_profile_image(100,100) %></td>
          <td></td>
        </tr>
        <tr>
          <td>name</td>
          <td>introduction</td>
        </tr>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.introduction %></td>
        </tr>
      </table>

  <div class="row">
       <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-default btn-block" do %>
         <i class="fas fa-user-cog"></i>
       <% end %>
  </div>

app/views/users/edit.html.erb
<!--ユーザープロフィール編集-->
<div class="container pt-3 pb-5">
  <div class="row">
    <div class="col-lg-5 mx-auto">

     <h2>User info</h2>

       <!--プロフィール編集時のエラー文-->
       <%= form_with model:@user, local: true do |form| %>
          <% if @user.errors.any? %>
            <div id="error_explanation">
              <h3><%= pluralize(@user.errors.count, "error") %> prohibited this product from being saved:</h3>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </div>
          <% end %>
        <% end %>

    <!--プロフィール編集画面のname,image,introduction-->
    <%= form_with model: @user do |f| %>

      <div class="form-group py-2">
        <label for="user_name">Name</label>
        <%= f.text_field :name,autofocus:true,id:"inputName",class:"form-control" %>
      </div>

      <div>
        <label for="user_image">Image</label><br>
           <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" ,class:"py-3" %>
      </div>

      <div class="form-group py-3">
        <label for="user_introduction">Introduction</label><br>
          <%= f.text_area :introduction ,autofocus:true,id:"inputInt",class:"form-control" %>
      </div>

      <%= f.submit 'Update User',class:"btn btn-secondary" %>
    <% end %>

   </div>
  </div>
 </div>

app/views/users/index.html.erb
<!--ユーザー一覧-->
<div class="container pt-3 pb-5">
  <div class="row">
    <div class="col-md-3 pr-1">

      <% if @book.errors.any? %>
        <%= @book.errors.count %> errors prohibited this book from being saved:<br/>
        <% @book.errors.full_messages.each do |message| %>
          <<%= message %>
        <% end %>
      <% end %>

   <%= render 'users/userinfo', user: @user %>

   <%= render 'books/newbook', book: @book %>
   </div>

   <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
            </tr>
  	      </thead>

          <% @users.each do |user| %>
            <tbody>
              <tr>
                <td>
                  <%= image_tag user.get_profile_image(100,100) %>
                </td>

                <td>
                  <%= user.name %>
                </td>

                <td>
                  <%= link_to"Show",user_path(user) %>
                </td>
              </tr>
            </tbody>
          <% end %>
	    </table>
      </div>
    </div>
  </div>

app/views/users/show.html.erb
<!--マイページ-->
<div class="container pt-3 pb-5">
  <div class="row">
    <div class="col-md-3 pr-1">

    <%= render 'users/userinfo', user: @user %>

    <%= render 'books/newbook', book: @book %>
    </div>

   <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
            </tr>
          </thead>

		  <% @books. each do |book| %>
		    <tbody>
		      <tr>
                <td>
                  <%= link_to user_path(book.user) do %>
                    <%= image_tag book.user.get_profile_image(100,100) %>
		          <% end %>
                </td>

		        <td>
		          <%= link_to book_path(book.id) do %>
		            <%= book.title %>
		          <% end %>
		        </td>

		        <td>
		          <%= book.body %>
		        </td>
		      <tr>
		    </tbody>
	      <% end %>
        </table>
      </di>
   </div>
</div>